### ISSUE TITLE
Bug  Odoo-Apps - Code-137Odoo 14 - Debian 10 - CloudClusters

### ISSUE THREAD

**Issue by IDMarcosR** [Code-137/odoo-apps#15]
Odoo Server Error

Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/cloudclusters/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/cloudclusters/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/cloudclusters/odoo/odoo/http.py", line 912, in call
    return self.method(*args, **kw)
  File "/cloudclusters/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/cloudclusters/odoo/odoo/addons/web/controllers/main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/cloudclusters/odoo/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-80>", line 2, in button_immediate_install
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/cloudclusters/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 197, in load_module_graph
    registry.setup_models(cr)
  File "/cloudclusters/odoo/odoo/modules/registry.py", line 269, in setup_models
    model._setup_base()
  File "/cloudclusters/odoo/odoo/models.py", line 2782, in _setup_base
    self._add_field(name, field.new())
  File "/cloudclusters/odoo/odoo/models.py", line 404, in _add_field
    field.setup_base(self, name)
  File "/cloudclusters/odoo/odoo/fields.py", line 278, in setup_base
    self._setup_attrs(model, name)
  File "/cloudclusters/odoo/odoo/fields.py", line 2290, in _setup_attrs
    "containing the specified option." % self
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/cloudclusters/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: payment.acquirer.provider: required selection fields must define an ondelete policy that implements the proper cleanup of the corresponding records upon module uninstallation. Please use one or more of the following policies: 'set default' (if the field has a default defined), 'cascade', or a single-argument callable where the argument is the recordset containing the specified option.

**Comment by fabioluna** [comment]
Consegue me detalhar quando está ocorrendo o erro?
