### ISSUE TITLE
Erro ao instalar módulo dos correios no odoo 14, instalado no computador local Windows

### ISSUE THREAD

**Issue by Elancedig** [Code-137/odoo-apps#19]
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "D:\odoo\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "D:\odoo\server\odoo\http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\server\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\server\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\server\odoo\http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\server\odoo\http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "D:\odoo\server\odoo\addons\web\controllers\main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "D:\odoo\server\odoo\addons\web\controllers\main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "D:\odoo\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\odoo\server\odoo\addons\base\models\ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\odoo\server\odoo\addons\base\models\ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\odoo\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\odoo\server\odoo\modules\loading.py", line 460, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\odoo\server\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\odoo\server\odoo\modules\loading.py", line 197, in load_module_graph
    registry.setup_models(cr)
  File "D:\odoo\server\odoo\modules\registry.py", line 273, in setup_models
    model._setup_base()
  File "D:\odoo\server\odoo\models.py", line 2787, in _setup_base
    self._add_field(name, field.new())
  File "D:\odoo\server\odoo\models.py", line 404, in _add_field
    field.setup_base(self, name)
  File "D:\odoo\server\odoo\fields.py", line 278, in setup_base
    self._setup_attrs(model, name)
  File "D:\odoo\server\odoo\fields.py", line 2328, in _setup_attrs
    "containing the specified option." % self
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\odoo\server\odoo\http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\server\odoo\http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: delivery.carrier.delivery_type: required selection fields must define an ondelete policy that implements the proper cleanup of the corresponding records upon module uninstallation. Please use one or more of the following policies: 'set default' (if the field has a default defined), 'cascade', or a single-argument callable where the argument is the recordset containing the specified option.

O erro ocorre no momento de instalar o módulo dos correios no odoo e somente com ele, fiz um fork da branch da versão 14 dos módulos do repositório e utilizei o delivery_correios de lá.
 Desde já muito obrigado pelo suporte!

**Comment by fabioluna** [comment]
Este erro já foi corrigido pelo PR #18
